name: rider-app
version: 0.1.0.0
github: "nammayatri/nammayatri"
license: AllRightsReserved
author: "nammayatri"
maintainer: "nammayatri"
copyright: "2023 Juspay Technologies Private Limited"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/nammayatri/nammayatri#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances
  - PackageImports

dependencies:
  - aeson
  - amazonka
  - amazonka-core
  - amazonka-ses
  - base >= 4.7 && < 5
  - base64-bytestring
  - bytestring
  - cryptonite
  - cryptostore >= 0.3.0.0
  - x509
  - euler-hs
  - lens
  - prometheus-client
  - wai-middleware-prometheus
  - prometheus-metrics-ghc
  - unliftio-core
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - http-media
  - text
  - wai
  - warp
  - time
  - record-hasfield
  - record-dot-preprocessor
  - servant-openapi3
  - openapi3
  - persistent
  - extra
  - text-conversions
  - dashboard-helper-api
  - http-types
  - containers
  - geohash == 1.0.1

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -fplugin=RecordDotPreprocessor

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -fhide-source-paths
    - -Werror
  dependencies:
    - mobility-core
    - beckn-spec
    - special-zone
executables:
  rider-app-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
    dependencies:
      - rider-app
      - mobility-core
      - beckn-spec
